/**
 * Generated by Goal Setting and Monitoring Agent
 * Task: Write a JavaScript function binaryGap(n) that returns the length of its longest binary gap (consecutive zeros surrounded by ones in binary representation). If it doesn't contain a binary gap, return 0.
 * 
 * Status: Passed
 */

/**
 * Returns the length of its longest binary gap (consecutive zeros surrounded by ones in binary representation).
 * If it doesn't contain a binary gap, return 0.
 *
 * @param {number} n - A positive integer
 * @returns {number} The length of the longest binary gap
 */
export default function binaryGap(n) {
  // Edge cases and validation: check if positive integer
  if (typeof n !== 'number' || n <= 0 || !Number.isInteger(n)) {
    return 0;
  }

  const binary = n.toString(2);
  let maxGap = 0;
  let currentGap = -1; // -1 means we haven't seen a '1' yet

  for (let i = 0; i < binary.length; i++) {
    if (binary[i] === '1') {
      if (currentGap >= 0) {
        maxGap = Math.max(maxGap, currentGap);
      }
      currentGap = 0; // reset/start counting zeros after this '1'
    } else if (currentGap >= 0) {
      currentGap++;
    }
  }

  return maxGap;
}