/**
 * CLI Runner for Goal Setting and Monitoring Pattern
 * ==================================================
 * Command-line runner to demonstrate goal breakdown, auditing, and self-refinement.
 * 
 * Usage:
 *   node index.js ["Your coding task"] ["Your comma-separated goals"] [--save]
 */

import fs from "fs";
import path from "path";
import { Ollama } from "ollama";
import { GoalMonitoringAgent } from "./agent.js";

// Colors for terminal formatting
const C_RESET = "\x1b[0m";
const C_GREEN = "\x1b[32m";
const C_YELLOW = "\x1b[33m";
const C_BLUE = "\x1b[34m";
const C_MAGENTA = "\x1b[35m";
const C_CYAN = "\x1b[36m";
const C_BOLD = "\x1b[1m";

// Default settings
const DEFAULT_TASK = "Write a JavaScript function isPalindrome(str) that returns true if the input string (ignoring case, spaces, and punctuation) is a palindrome, and false otherwise.";
const DEFAULT_GOALS = "Handles edge cases, passes all test cases";

// Automated test cases to run in sandbox to ensure correctness
const PALINDROME_TEST_CASES = [
  { input: "A man, a plan, a canal: Panama", expected: true },
  { input: "race a car", expected: false },
  { input: " ", expected: true },
  { input: "a", expected: true },
  { input: "No 'x' in Nixon", expected: true }
];

async function main() {
  // Parse command line arguments
  const args = process.argv.slice(2);
  
  // Filter out flags
  const saveFlag = args.includes("--save");
  const cleanArgs = args.filter(a => !a.startsWith("-"));

  const task = cleanArgs[0] || DEFAULT_TASK;
  const goals = cleanArgs[1] || DEFAULT_GOALS;

  // Only pass the automated tests if we are running the default task
  const isDefaultTask = task === DEFAULT_TASK;
  const testCases = isDefaultTask ? PALINDROME_TEST_CASES : null;
  const functionName = isDefaultTask ? "isPalindrome" : null;

  console.log("═══════════════════════════════════════════════════════════");
  console.log("  🎯  GOAL SETTING AND MONITORING PATTERN — CLI RUNNER");
  console.log("═══════════════════════════════════════════════════════════\n");
  console.log(`${C_BOLD}Use Case Description:${C_RESET} ${task}`);
  console.log(`${C_BOLD}High-Level Goals:${C_RESET} ${goals}\n`);

  const ollama = new Ollama({ host: "http://localhost:11434" });
  const agent = new GoalMonitoringAgent(ollama, "llama3.2");

  // Callbacks for beautiful logging
  const callbacks = {
    onTrace: (message, type) => {
      switch (type) {
        case "info":
          console.log(`${C_CYAN}[System] ${message}${C_RESET}`);
          break;
        case "warn":
          console.log(`${C_YELLOW}[Warning] ${message}${C_RESET}`);
          break;
        case "checklist":
          console.log(`${C_GREEN}  * ${message}${C_RESET}`);
          break;
        case "header":
          console.log(`\n${C_BOLD}${C_BLUE}${message}${C_RESET}`);
          break;
        case "generator-start":
          console.log(`${C_CYAN}[Generator] ${message}${C_RESET}`);
          break;
        case "code":
          console.log(`\n${C_YELLOW}${message}${C_RESET}\n`);
          break;
        case "reviewer-start":
          console.log(`${C_CYAN}[Reviewer] ${message}${C_RESET}`);
          break;
        case "review":
          console.log(`\n${C_MAGENTA}${message}${C_RESET}\n`);
          break;
        case "judge-start":
          console.log(`${C_CYAN}[Judge] ${message}${C_RESET}`);
          break;
        case "judge-result":
          console.log(`${C_BOLD}${C_GREEN}[Judge Result] ${message}${C_RESET}`);
          break;
        case "success":
          console.log(`\n${C_BOLD}${C_GREEN}🎉 SUCCESS: ${message}${C_RESET}\n`);
          break;
        case "refining":
          console.log(`${C_YELLOW}[Refining] ${message}${C_RESET}`);
          break;
        default:
          console.log(message);
      }
    }
  };

  const startTime = Date.now();
  const result = await agent.run(task, goals, 4, callbacks, testCases, functionName);
  const duration = ((Date.now() - startTime) / 1000).toFixed(1);

  console.log("═══════════════════════════════════════════════════════════");
  console.log(`  Execution Complete!`);
  console.log(`    - Status:      ${result.success ? "💚 PASSED" : "❤️ FAILED (Max Iterations Reached)"}`);
  console.log(`    - Iterations:  ${result.iterationsRun}`);
  console.log(`    - Duration:    ${duration}s`);
  console.log("═══════════════════════════════════════════════════════════\n");

  // Save code to a file
  if (result.success || saveFlag) {
    const filename = functionName 
      ? `${functionName.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()}.js` 
      : "output.js";
    const commentHeader = `/**
 * Generated by Goal Setting and Monitoring Agent
 * Task: ${task}
 * 
 * Goals Checklist Evaluation:
${result.checklist.map((c, i) => ` *  - [x] ${c}`).join("\n")}
 * 
 * Status: ${result.success ? "Passed" : "Failed"}
 * Iterations: ${result.iterationsRun}
 */

`;
    
    const finalFileContent = commentHeader + result.finalCode;
    const outputPath = path.join(process.cwd(), filename);
    fs.writeFileSync(outputPath, finalFileContent, "utf-8");
    console.log(`${C_GREEN}💾 Output file saved to: ${outputPath}${C_RESET}\n`);
  }
}

main().catch(err => {
  console.error("\n❌ Execution Error:", err.message);
  process.exit(1);
});
