/**
 * Generated by Goal Setting and Monitoring Agent
 * Task: Write a JavaScript function isPalindrome(str) that returns true if the input string (ignoring case, spaces, and punctuation) is a palindrome, and false otherwise.
 * 
 * Goals Checklist Evaluation:
 *  - [x] Handles null/undefined input correctly by throwing an error
 *  - [x] Passes all test cases with the specified test data (e.g., 'Madam', 'hello', 'A man, a plan, a canal: Panama')
 *  - [x] Uses standard ES6 export syntax for module exports
 *  - [x] Does not include any unused imports or variables
 * 
 * Status: Passed
 * Iterations: 2
 */

export default function isPalindrome(str) {
  if (!str) {
    throw new Error('Input cannot be null or undefined');
  }

  str = str.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();

  const reversedStr = str.split('').reverse().join('');

  return str === reversedStr;
}